# Generated by Django 5.0.1 on 2024-01-31 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='base.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='base.user')),
            ],
            options={
                'unique_together': {('user', 'follower')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='followers_list',
            field=models.ManyToManyField(through='base.UserFollowers', to='base.user'),
        ),
    ]
